title: "The Social Data Science Alliance"
description: "An organisation of researchers planning and conducting research enabled by the EU's Digital Services Act."
baseurl: "" # Leave blank for GitHub Pages
url: "https://social-data-science-alliance.github.io"
theme: minima
plugins:
  - jekyll-sitemap

sass:
  sass_dir: _sass

markdown: kramdown
kramdown:
  input: GFM
