services:
  jekyll:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
      - "35729:35729"
    volumes:
      - .:/site
    command: bundle exec jekyll serve --host 0.0.0.0 --port 4001 --livereload
